import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./header";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Plis Jangan Ngelu",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Header />
      <div className="bg-home bg-no-repeat bg-cover">
         <div className="bg-brown w-screen">
          </div>
          </div>
        {children}
      </body>
    </html>
  );
}
